"""Change Event start & end into day & period

Revision ID: 33e3b2d5d77d
Revises: 4d48f6961b08
Create Date: 2014-08-15 13:56:03.159000

"""

# revision identifiers, used by Alembic.
revision = '33e3b2d5d77d'
down_revision = '4d48f6961b08'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
#from sqlalchemy import sql


# Make a temporary model of the event table
connection = op.get_bind()
event_table = sa.Table(
    'event',
    sa.MetaData(),
    sa.Column('id', sa.Integer),
    sa.Column('day', sa.Date),
    sa.Column('period', sa.String),
    sa.Column('start', sa.DateTime),
    sa.Column('end', sa.DateTime),
)

def upgrade():
    # Add new columns as nullable
    op.add_column('event', sa.Column('day', sa.Date()))
    op.add_column('event', sa.Column('period', sa.String(length=10)))

    # Populate new columns
    for event in connection.execute(event_table.select()):
        # Work out what the new values should be
        day = event.start.date()
        if event.start.hour == 8:
            if event.end.hour == 20:
                period = 'AFD'
            else:
                period = 'AM'
        else:
            period = 'PM'

        # Update the record
        connection.execute(
            event_table.update().where(
                event_table.c.id == event.id
            ).values(
                day=day,
                period=period,
            )
        )

    # Make columns not nullable
    op.alter_column('event', 'day', nullable=False)
    op.alter_column('event', 'period', nullable=False)

    # Remove old columns
    op.drop_column('event', 'start')
    op.drop_column('event', 'end')


def downgrade():
    raise Exception('Write your own downgrade script!')
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event', sa.Column('end', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.add_column('event', sa.Column('start', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('event', 'period')
    op.drop_column('event', 'day')
    ### end Alembic commands ###
